---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'bootstrap'
Populate:
  include_yaml_fixtures:
    - 'mysite/fixtures/pages.yml'
    - 'mysite/fixtures/calendars.yml'
    - 'mysite/fixtures/2015/events-01.yml'
    - 'mysite/fixtures/2015/events-02.yml'
    - 'mysite/fixtures/2015/events-03.yml'
    - 'mysite/fixtures/2015/events-04.yml'
    - 'mysite/fixtures/2015/events-05.yml'
    - 'mysite/fixtures/2015/events-06.yml'
    - 'mysite/fixtures/2015/events-07.yml'
    - 'mysite/fixtures/2015/events-08.yml'
    - 'mysite/fixtures/2015/events-09.yml'
    - 'mysite/fixtures/2015/events-10.yml'
    - 'mysite/fixtures/2015/events-11.yml'
    - 'mysite/fixtures/2015/events-12.yml'
    - 'mysite/fixtures/2016/events-01.yml'
    - 'mysite/fixtures/2016/events-02.yml'
    - 'mysite/fixtures/2016/events-03.yml'
    - 'mysite/fixtures/2016/events-04.yml'
    - 'mysite/fixtures/2016/events-05.yml'
    - 'mysite/fixtures/2016/events-06.yml'
    - 'mysite/fixtures/2016/events-07.yml'
    - 'mysite/fixtures/2016/events-08.yml'
    - 'mysite/fixtures/2016/events-09.yml'
    - 'mysite/fixtures/2016/events-10.yml'
    - 'mysite/fixtures/2016/events-11.yml'
    - 'mysite/fixtures/2016/events-12.yml'
    - 'mysite/fixtures/2017/events-01.yml'
    - 'mysite/fixtures/2017/events-02.yml'
    - 'mysite/fixtures/2017/events-03.yml'
    - 'mysite/fixtures/2017/events-04.yml'
    - 'mysite/fixtures/2017/events-05.yml'
    - 'mysite/fixtures/2017/events-06.yml'
    - 'mysite/fixtures/2017/events-07.yml'
    - 'mysite/fixtures/2017/events-08.yml'
    - 'mysite/fixtures/2017/events-09.yml'
    - 'mysite/fixtures/2017/events-10.yml'
    - 'mysite/fixtures/2017/events-11.yml'
    - 'mysite/fixtures/2017/events-12.yml'
  truncate_objects:
    - Calendar
    - Event
    - SiteTree