---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'bootstrap'
Populate:
  include_yaml_fixtures:
    - 'mysite/fixtures/pages.yml'
    - 'mysite/fixtures/calendars.yml'
    - 'mysite/fixtures/events-june.yml'
    - 'mysite/fixtures/events-july.yml'
    - 'mysite/fixtures/events-august.yml'
    - 'mysite/fixtures/events-september.yml'
  truncate_objects:
    - Calendar
    - Event